// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web2Projekat.Infrastructure.DBContext;

#nullable disable

namespace Web2Projekat.Migrations.ArtikliDb
{
    [DbContext(typeof(ArtikliDbContext))]
    [Migration("20230916140043_NewDB")]
    partial class NewDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Web2Projekat.Infrastructure.DBO.ArtikalDBO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Cena")
                        .HasColumnType("REAL");

                    b.Property<string>("Fotografija")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kolicina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KolicinaNaStanju")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prodavac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID")
                        .HasName("PK_IDArikla");

                    b.ToTable("Artikal", (string)null);
                });

            modelBuilder.Entity("Web2Projekat.Infrastructure.DBO.KorpaArtikalDBO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtikalId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cena")
                        .HasColumnType("REAL");

                    b.Property<int>("Kolicina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PorudzbinaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK_Id");

                    b.HasIndex("ArtikalId");

                    b.HasIndex("PorudzbinaId");

                    b.ToTable("KorpaArtikli", (string)null);
                });

            modelBuilder.Entity("Web2Projekat.Infrastructure.DBO.PorudzbinaDBO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresaDostave")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumPorucivanja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kupac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UkupnaCena")
                        .HasColumnType("REAL");

                    b.Property<double>("VremeDostave")
                        .HasColumnType("REAL");

                    b.HasKey("Id")
                        .HasName("PK_Id");

                    b.ToTable("Porudzbine", (string)null);
                });

            modelBuilder.Entity("Web2Projekat.Infrastructure.DBO.KorpaArtikalDBO", b =>
                {
                    b.HasOne("Web2Projekat.Infrastructure.DBO.ArtikalDBO", "Artikal")
                        .WithMany()
                        .HasForeignKey("ArtikalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web2Projekat.Infrastructure.DBO.PorudzbinaDBO", "Porudzbina")
                        .WithMany("listaArtikla")
                        .HasForeignKey("PorudzbinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("Porudzbina");
                });

            modelBuilder.Entity("Web2Projekat.Infrastructure.DBO.PorudzbinaDBO", b =>
                {
                    b.Navigation("listaArtikla");
                });
#pragma warning restore 612, 618
        }
    }
}
